### ISSUE TITLE
Codiusd: Selftest Error 

### ISSUE THREAD

**Issue by GaetanoH** [codius/codiusd#139]
Hello,

After upgrading to 1.2.5 I get this error: 

`018-08-17T19:53:17.702Z codiusd:HttpServer info listening at https://codius
2018-08-17T19:53:17.732Z codiusd:SelfTest error { FetchError: request to https://codius/pods?duration=300 failed, reason: connect ECONNREFUSED 10.132.0.2:443
    at ClientRequest.<anonymous> (/usr/lib/node_modules/codiusd/node_modules/node-fetch/lib/index.js:1345:11)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to https://codius/pods?duration=300 failed, reason: connect ECONNREFUSED 10.132.0.2:443',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }
2018-08-17T19:53:17.735Z codiusd:SelfTest error Error: Self test failed: Upload Status=false Http Connection=false WebSocket Connection=false
    at SelfTest.run (/usr/lib/node_modules/codiusd/src/services/SelfTest.ts:202:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by mmaton** [comment]
Hello, try giving your host more tries at booting the selfTest image by adding this to your /etc/systemd/system/codiusd.service file: 
`Environment="CODIUS_SELF_TEST_RETRIES=10"`

**Comment by GaetanoH** [comment]
Hello, this was fixed using by setting the correct hostname on my server. But now my other server has the same issue. Codius upload tool says this: `504 Gateway Timeout: The codius host never responded to the request.`

However when I do all updates for 1.2.5 and do 
`systemctl restart hyperd` 
` systemctl restart nginx` 
` systemctl restart codiusd && journalctl -u codiusd -f` 

I get that everything went perfect...

**Comment by GaetanoH** [comment]
I did that, fixed nothing still getting:

`==================================
codiusd
==================================

2018-08-22T20:54:33.671Z codiusd:App info starting codiusd...
2018-08-22T20:54:33.846Z connector:leveldown-store info initialize database. path=/var/lib/codius/connector.db
2018-08-22T20:54:33.850Z connector:route-broadcaster info generated random routing secret.
2018-08-22T20:54:33.859Z connector:accounts info add account. accountId=parent
2018-08-22T20:54:33.861Z connector:accounts info add account. accountId=child
2018-08-22T20:54:33.876Z connector:accounts warn DEPRECATED: plugin accessed deprecated _store property. accountId=child
2018-08-22T20:54:33.876Z connector:accounts warn DEPRECATED: plugin accessed deprecated _store property. accountId=child
RTNETLINK answers: File exists
RTNETLINK answers: File exists
2018-08-22T20:54:33.903Z connector:balance-middleware warn (!!!) balance middleware NOT enabled for account, this account can spend UNLIMITED funds. accountId=parent
2018-08-22T20:54:33.905Z connector:balance-middleware warn (!!!) balance middleware NOT enabled for account, this account can spend UNLIMITED funds. accountId=child
2018-08-22T20:54:33.918Z connector:accounts info setting ilp address. oldAddress=unknown newAddress=g.mofu.child.ctTCsf9n7ttB4YpM-5y3w7m64clOjpnbbwqDh57QvEA.local.R_qa9ac0pyuAx0W1NHqNC9xWW9Lk3QPwzpFuX8YWBeE
2018-08-22T20:54:33.928Z connector:admin-api info listen called
2018-08-22T20:54:33.929Z connector:app info connector ready (republic attitude). address=g.mofu.child.ctTCsf9n7ttB4YpM-5y3w7m64clOjpnbbwqDh57QvEA.local.R_qa9ac0pyuAx0W1NHqNC9xWW9Lk3QPwzpFuX8YWBeE
2018-08-22T20:54:33.956Z codiusd:HttpServer info listening at https://codius.gaetanoherman.be
2018-08-22T20:54:33.991Z codiusd:SelfTest error { FetchError: request to https://codius.gaetanoherman.be/pods?duration=300 failed, reason: connect ECONNREFUSED 127.0.0.1:443
    at ClientRequest.<anonymous> (/usr/lib/node_modules/codiusd/node_modules/node-fetch/lib/index.js:1345:11)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to https://codius.gaetanoherman.be/pods?duration=300 failed, reason: connect ECONNREFUSED 127.0.0.1:443',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }
2018-08-22T20:54:33.996Z codiusd:SelfTest error Error: Self test failed: Upload Status=false Http Connection=false WebSocket Connection=false
    at SelfTest.run (/usr/lib/node_modules/codiusd/src/services/SelfTest.ts:202:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)`
