### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by Soolan** [codius/codiusd#89]
Hello,
Thanks for this wonderful package.
I tried to setup a codius host on Google Cloud Platform.
I already have a toast  wallet with 25 xrp in it + subdomain (codius1.soolan.com) pointing to my VM instance ip and installed all the required libs and packages to get this going.
I had no problem with SSL certificate as well. But I got Bad Gateway error when I try to visit: https://codius1.soolan.com/version

Looking at the nginx error logs, it says
```
2018/07/09 02:47:13 [error] 25800#0: *18 connect() failed (111: Connection refused) while connecting to upstream, client: 129.126.203.71, server: , request: "GET /version HTTP/1.1", upstream: "http://127.0.0.1:3000/version", host: "codius1.soolan.com"
```
Here is the output for  netstat -tulpn
```Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      25799/nginx: master 
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      25799/nginx: master 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1109/sshd           
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1105/master         
tcp6       0      0 :::80                   :::*                    LISTEN      25799/nginx: master 
tcp6       0      0 :::22                   :::*                    LISTEN      1109/sshd           
tcp6       0      0 ::1:25                  :::*                    LISTEN      1105/master         
udp        0      0 127.0.0.1:323           0.0.0.0:*                           330/chronyd         
udp        0      0 0.0.0.0:68              0.0.0.0:*                           574/dhclient        
udp6       0      0 ::1:323           ```

I followed the steps for trouble shooting the 502 issue (trying to make moneyd and codiusd listening, etc). yet still no luck.
When I start moneyd in debug mode I see this error in its logs:

```2018-07-09T02:40:35.205Z connector:app error TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:207:11)
    at Object.encodeChannelProof (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-paychan-shared/lib/util.js:110:12)
    at Plugin._connect (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-asym-client/index.js:186:35)
```
Any idea what might be wrong?
Thank you very much.

**Comment by traviscrist** [comment]
It looks like your codiusd is not running which is likely due to moneyd not starting up correctly. 

Try deleting your current `~/.moneyd.json` then running `moneyd xrp:configure` and then starting up moneyd with `moneyd xrp:start`

**Comment by Soolan** [comment]
Thank you so much for your response @traviscrist 
I followed your instructions and after starting the moneyd ran into the following problem:
```
starting moneyd
2018-07-10T03:06:27.353Z connector:route-broadcaster info generated random routing secret.
2018-07-10T03:06:27.362Z connector:accounts info add account. accountId=parent
2018-07-10T03:06:27.364Z connector:accounts warn DEPRECATED: plugin accessed deprecated _log property. accountId=parent
2018-07-10T03:06:27.365Z connector:accounts info add account. accountId=local
2018-07-10T03:06:27.389Z connector:accounts warn DEPRECATED: plugin accessed deprecated _log property. accountId=local
2018-07-10T03:06:27.390Z connector:accounts warn DEPRECATED: plugin accessed deprecated _store property. accountId=local
2018-07-10T03:06:27.390Z connector:accounts warn DEPRECATED: plugin accessed deprecated _store property. accountId=local
2018-07-10T03:06:31.317Z connector:app error TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:207:11)
    at Object.encodeChannelProof (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-paychan-shared/lib/util.js:110:12)
    at Plugin._connect (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-asym-client/index.js:186:35)
```

**Comment by njlie** [comment]
What version of moneyd are you using? You can check by using `moneyd --version`.

**Comment by traviscrist** [comment]
Thanks, there is a new version 4.0.1 of moneyd out, can you try upgrading to it and then starting moneyd?

**Comment by Soolan** [comment]
Thank you @traviscrist 
I upgraded to ver 4.0.1, 
deleted ~/.moneyd.json
and ran:
```
$ moneyd xrp:configure
$ moneyd xrp:start
```

but got the same error:
```
2018-07-12T02:32:16.332Z connector:route-broadcaster info generated random routing secret.
2018-07-12T02:32:16.340Z connector:accounts info add account. accountId=parent
2018-07-12T02:32:16.342Z connector:accounts warn DEPRECATED: plugin accessed deprecated _log property. accountId=parent
2018-07-12T02:32:16.343Z connector:accounts info add account. accountId=local
2018-07-12T02:32:20.387Z connector:app error TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:207:11)
    at Object.encodeChannelProof (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-paychan-shared/lib/util.js:110:12)
    at Plugin._connect (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-asym-client/index.js:186:35)
```

**Comment by Thijxx** [comment]
I had this same issue and in the end it became clear I needed 36+ XRP and not 25 in my wallet. Worth a try :)

**Comment by traviscrist** [comment]
@Thijxx thanks for pointing that out, that's likely the issue. 

@Soolan can you try making sure you have 36+ XRP in the wallet?

**Comment by Soolan** [comment]
@Thijxx Thank you so much. That was exactly the problem. There is nothing wrong with moneyd.
Thank you all @traviscrist and @njlie and @Thijxx
