### ISSUE TITLE
Host offline after updating to 1.1.3

### ISSUE THREAD

**Issue by SneakyFish5** [codius/codiusd#99]
My host is down and I can't reach it at https://codius.sneakyfish5.xyz/version
I just upgraded to 1.1.3, ran `systemctl daemon-reload` and `systemctl restart codiusd` and now my host is unreachable. I checked codiusd logs and heres the only error I see, which shouldn't affect anything.

```
Jul 13 02:06:12 codius.sneakyfish5.xyz codiusd[19752]: 390,
Jul 13 02:06:12 codius.sneakyfish5.xyz codiusd[19752]: 'https://codius1.auminijay.xyz' ]
Jul 13 02:06:12 codius.sneakyfish5.xyz codiusd[19752]: 2018-07-13T02:06:12.496Z follow-redirects debug options { protocol: 'https:',
Jul 13 02:06:12 codius.sneakyfish5.xyz codiusd[19752]: maxRedirects: 21,
Jul 13 02:06:35 codius.sneakyfish5.xyz codiusd[19752]: 2018-07-13T02:06:35.388Z connector:ilp-plugin-btp[parent]:trace debug processing btp packet {"type":1,"requestId":2350220395,"data":{"protocolData":[{"protocolName":"ilp","contentType":0,"data":{"type":"Buffer","data":[14,118,70,48,48,59,103,46,115,99,121,108,108,97,46,99,108,105,101,110,116,46,55,102,108,109,116,116,118,100,76,122,89,108,45,45,69,104,109,118,101,76,105,84,105,111,77,57,118,51,119,69,49,75,101,85,72,68,107,100,117,90,45,49,99,53,99,97,110,110,111,116,32,112,114,111,99,101,115,115,32,114,111,117,116,101,32,99,111,110,116,114,111,108,32,109,101,115,115,97,103,101,115,32,102,114,111,109,32,110,111,110,45,112,101,101,114,115,46,0]}}]}}
Jul 13 02:06:35 codius.sneakyfish5.xyz codiusd[19752]: 2018-07-13T02:06:35.388Z connector:ilp-plugin-btp[parent]:trace debug received BTP packet (TYPE_RESPONSE, RequestId: 2350220395): {"protocolData":[{"protocolName":"ilp","contentType":0,"data":{"type":"Buffer","data":[14,118,70,48,48,59,103,46,115,99,121,108,108,97,46,99,108,105,101,110,116,46,55,102,108,109,116,116,118,100,76,122,89,108,45,45,69,104,109,118,101,76,105,84,105,111,77,57,118,51,119,69,49,75,101,85,72,68,107,100,117,90,45,49,99,53,99,97,110,110,111,116,32,112,114,111,99,101,115,115,32,114,111,117,116,101,32,99,111,110,116,114,111,108,32,109,101,115,115,97,103,101,115,32,102,114,111,109,32,110,111,110,45,112,101,101,114,115,46,0]}}]}
Jul 13 02:06:35 codius.sneakyfish5.xyz codiusd[19752]: 2018-07-13T02:06:35.388Z connector:ccp-receiver[parent] debug route control message was rejected. rejection={"code":"F00","triggeredBy":"g.scylla.client.7flmttvdLzYl--EhmveLiTioM9v3wE1KeUHDkduZ-1c","message":"cannot process route control messages from non-peers.","data":{"type":"Buffer","data":[]}}
Jul 13 02:06:35 codius.sneakyfish5.xyz codiusd[19752]: 2018-07-13T02:06:35.388Z connector:ccp-receiver[parent] debug failed to set route control information on peer. error=Error: route control message rejected.
Jul 13 02:06:35 codius.sneakyfish5.xyz codiusd[19752]: at plugin.sendData.then.data (/usr/lib/node_modules/codiusd/node_modules/ilp-connector/src/routing/ccp-receiver.ts:174:17)
Jul 13 02:06:35 codius.sneakyfish5.xyz codiusd[19752]: at process._tickCallback (internal/process/next_tick.js:68:7)
```

I also ran a debug script that you can see here: https://github.com/xrp-community/codius-install

I saw an error there where it said:
```
==================================
codiusd
==================================


/usr/lib/node_modules/codiusd/src/services/Config.ts:58
      throw new Error('Codiusd requires CODIUS_PUBLIC_URI to be set')
            ^
Error: Codiusd requires CODIUS_PUBLIC_URI to be set
    at new Config (/usr/lib/node_modules/codiusd/src/services/Config.ts:58:13)
    at construct (/usr/lib/node_modules/codiusd/node_modules/reduct/index.ts:34:12)
    at reduct (/usr/lib/node_modules/codiusd/node_modules/reduct/index.ts:59:7)
    at new App (/usr/lib/node_modules/codiusd/src/services/App.ts:26:19)
    at construct (/usr/lib/node_modules/codiusd/node_modules/reduct/index.ts:34:12)
    at reduct (/usr/lib/node_modules/codiusd/node_modules/reduct/index.ts:59:7)
    at Object.<anonymous> (/usr/lib/node_modules/codiusd/src/index.ts:8:23)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)

==================================
```

So I checked my config but it looks all good to me. I'll paste it below for you to check.

```
[Unit]
Description=Codiusd
After=network.target nss-lookup.target
[Service]
ExecStart=/usr/bin/npm start
Environment="DEBUG=*"
Environment="CODIUS_PUBLIC_URI=https://codius.sneakyfish5.xyz"
Environment="CODIUS_COST_PER_MONTH=10"
Environment="CODIUS_ADDITIONAL_HOST_INFO=true"
Environment="CODIUS_MAX_MEMORY_FRACTION=0.80"
WorkingDirectory=/usr/lib/node_modules/codiusd
Restart=always
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=codiusd
User=root
Group=root
[Install]
WantedBy=multi-user.target
```

I would love to have any help you can provide me, and maybe figure this out, as I've never seen something like this before and the troubleshooting docs don't say anything about this.

**Comment by njlie** [comment]
Can you double check your DNS? Your host isn't resolving to any IP addresses.

**Comment by SneakyFish5** [comment]
I checked my DNS on namecheap, it seems to be running all good. Is there something specific I should be looking for?

**Comment by traviscrist** [comment]
Earlier we were unable to even reach codius.sneakyfish5.xyz, I just tried now and its now resolving. It also shows your host is running 1.1.3 at https://codius.sneakyfish5.xyz/version and I can upload a contract successfully to it.

**Comment by sharafian** [comment]
Sounds like this is resolved
